Feature:add user related functionality and tests
yuriamm/hello pull request #2
Opened 2021-02-18 09:44 UTC by yuriamm

Sign up, login, and logout functionality are implemented in this PR. UI hasn't been implemented yet so is still using the default one from phoenix project.

2021-02-18 10:30 UTC, MasashiYokota requested changes
インデントがめちゃくちゃなのは良くないですね。
エディタの設定を見直して下さい。

2021-02-18 10:30 UTC, MasashiYokota commented on src/lib/hello/user.ex
> +    end
`@type` でスキーマの型を定義しましょう

2021-02-18 10:30 UTC, MasashiYokota commented on src/lib/hello/user.ex
> +        |> encrypt_password
```suggestion
        |> encrypt_password()
```
mix formatかけてください。

2021-02-18 10:30 UTC, MasashiYokota commented on src/lib/hello_web/controllers/login_controller.ex
> +        user = repo.get_by(User, username: params["username"])
このロジックは、contextに吐き出した方がよいですね。

2021-02-18 10:30 UTC, MasashiYokota commented on src/lib/hello/user.ex
> +    use Ecto.Schema
elixirのインデントは2です。全ファイル修正して下さい。

2021-02-18 10:30 UTC, MasashiYokota commented on src/test/hello_web/controllers/logout_controller_test.exs
> +end
インデントおかしいです

2021-02-18 10:30 UTC, MasashiYokota commented on src/lib/hello_web/controllers/login_controller.ex
> +  end
これ、どんなアクションですか？routerにセットされていませんが。

2021-02-18 13:07 UTC, MasashiYokota commented on src/lib/hello_web.ex
> +      end
この謎のpublic functionはなんですか？

2021-02-18 13:08 UTC, MasashiYokota commented on src/lib/hello_web/controllers/registration_controller.ex
> +  end
これは、contextに書いて下さい。controllerの仕事じゃないです

2021-02-18 13:09 UTC, MasashiYokota commented on src/lib/hello/login.ex
> +  @spec get_current_user(Plug.Conn.t()) :: Plug.Conn.t()
返り値の型あっていますか？

2021-02-18 13:09 UTC, MasashiYokota commented on src/lib/hello/login.ex
> +
`@doc`書いていないです

2021-02-18 13:15 UTC, MasashiYokota commented on src/lib/hello/login.ex
> +  def login(params, repo) do
関数設計が変なので、もう一度考え直しましょう！

2021-02-18 13:15 UTC, MasashiYokota commented on src/lib/hello/login.ex
> +  end
パターンマッチ使いましょう。

2021-02-18 13:16 UTC, MasashiYokota commented on src/priv/repo/migrations/20210213092327_create_users.exs
> +  end
シンプルなものは、down書く必要ないです。

2021-02-18 16:36 UTC, yuriamm commented on src/lib/hello/login.ex
> +    #IS IT EVEN POSSIBLE TO PATTERN MATCH WHEN HANDLING ERRORS...
🤯

2021-02-18 16:39 UTC, yuriamm commented on src/lib/hello_web/views/page_view.ex
> +  # CURRENT USER ID IS NOT PASSED IN HERE
It didn't pass into conn.assigns so just got the session.

2021-02-20 04:23 UTC, poly65536 requested changes
そこそこコメントしたので確認お願いします。
あと、モジュールやコントローラーの切り方が結構独特な感じになっているので、もう少し他のサイトやプログラムを参考にしたほうが良いと思います。まずはREST APIについて調べてみると良さそうです。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello/accounts.ex
> +  @spec create_user(map()) :: {:ok, User.t() | nil} | {:error, Ecto.Changeset.t()}
`User.t() | nil`となっていますが、この`nil`は必要ですか？`Repo.insert`の定義を確認したり、仮に`nil`が入るなら`nil`の代わりにエラーにしたほうが良いかなどを考えてみると良いと思います。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello/accounts/user.ex
> +      changeset
パスワードがないときはエラーで落としたほうが良いんじゃ・・・？

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello/login.ex
> +  @spec login(map()) :: {:ok, User.t() | nil} | :error
ここのnilも確認したほうが良さそうですね。そもそも、`user`が`nil`だったら`user.encrypted_password`の部分がエラーになってしまいます。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello/login.ex
> +defmodule Hello.Login do
`Login`よりも`Session`とか`User`みたいなモジュール名のほうが良いと思います。今後ログアウト機能とかを作る度に別モジュールを作らないといけないのはめんどくさいしなんか変なので。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello_web/controllers/login_controller.ex
> +defmodule HelloWeb.LoginController do
ここも`LoginController`を作るのではなく、`SessionController`や`UserController`みたいにして意味ごとにまとめると良いと思います。詳しくは、"REST"と呼ばれる通信の規約を調べてみたり、Webサービスのコントローラを他の人がどう作っているのかを参考にすると良いと思います。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello/login.ex
> +  @spec login(map()) :: {:ok, User.t() | nil} | :error
エラー時の返り値が`:error`になっていますが、実際に返しているのは`{:error, "..."}`になっています。呼び出し先では`:error`を想定しているので多分正常にプログラムが動かなくなると思います。実際に動かすときにログインできないパスワードを試したり、このケースを想定したテストを追加したほうが良いです。
あと、型チェックのために`mix dialyzer`もたまに走らせたほうが良いかも知れません。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello_web/router.ex
> +    get "/signup", RegistrationController, :index
routerの`resources`を調べてみましょう。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello_web/templates/login/index.html.eex
> +<% end %>
末尾改行を入れましょう。VSCodeで保存時に末尾改行を整理してくれる設定があったはずなので、それを設定すると良いと思います。ついでに行末空白等の設定もしておくと便利です。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello_web/views/page_view.ex
> +  def is_logged_in(conn) do
viewは表示するページのことしかやらないほうが良いので、この関数は`Session`モジュールとかを作ってそっちに移したほうが良いです。

2021-02-20 04:23 UTC, poly65536 commented on src/test/hello_web/controllers/login_controller_test.exs
> +  @invalid_password %{username: "username", password: "incorrect_password"}
`@invalid_username`と`@invalid_password`の違いってなんでしょうか？

2021-02-20 04:23 UTC, poly65536 commented on src/test/hello_web/controllers/login_controller_test.exs
> +    assert post(conn, Routes.login_path(conn, :create), session: @invalid_password).status == 200
この2つのassertは別のテストに分けたほうが良いと思います。あと、`describe`を使ってログインできるときとログインできないときのコンテキストに分けてみましょう。

2021-02-20 04:23 UTC, poly65536 commented on src/lib/hello/accounts.ex
> +defmodule Hello.Accounts do
基本的にpublicに公開している関数はテストを書いたほうが良い（`changeset`等は除く）ので、`Accounts`モジュール等の関数はテストを書かないといけないです。

2021-02-26 10:05 UTC, MasashiYokota commented
LGTM 👍

2021-02-26 10:05 UTC, merged