Feature: add tweet related functionality
yuriamm/hello pull request #3
Opened 2021-02-26 14:09 UTC by yuriamm

This PR is to add tweet related functionality.

2021-02-27 10:50 UTC, poly65536 commented on src/lib/hello/posts.ex
> +    |> Repo.get(id)
有志のスタイルガイドですが、パイプ演算子`|>`は一回しか使わないなら、直接関数を適用したほうが良いとされてます。
https://github.com/christopheradams/elixir_style_guide#avoid-single-pipelines

2021-02-27 10:50 UTC, poly65536 commented on src/lib/hello/posts/tweet.ex
> +    belongs_to :user, Hello.Accounts.User, foreign_key: :user_id
`Hello.Accounts.User`のように書かずに`alias`したほうが良いです。あと、この場合`foreign_key: :user_id`はなくても動きそうな気がするんですが、どうでしょうか？

2021-02-27 10:50 UTC, poly65536 commented on src/lib/hello_web/controllers/tweet_controller.ex
> +    {:ok, _} = Posts.delete_tweet(tweet)
controllerに余計なロジックを入れないほうが良いので、`Posts.delete_tweet`の引数を`tweet_id`にしても良いんじゃないかと思いました。

2021-02-27 10:50 UTC, poly65536 commented on src/lib/hello_web/templates/tweet/index.html.eex
> +<% end %>
インデントが変な感じになってます

2021-02-27 10:50 UTC, poly65536 commented on src/priv/repo/migrations/20210220044723_create_tweets.exs
> +      add :tweet, :string, size: 140, null: false
データベースで長い文字列のカラムを作るときは`:string`より`:text`を使ったほうが良かった気がします。（正確には覚えてないので調べてみてください）

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello/posts/tweet_test.exs
> +    test "should insert data into tweets table when it has valid data", %{user: user} do
insertはしないので`"should be valid ..."`で良さそう

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello/posts_test.exs
> +  def user_fixture do
このモジュール内でしか使ってないと思うのでprivateにしましょう

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello/posts_test.exs
> +      user = user_fixture()
userを`setup`で作りましょう！

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello/posts_test.exs
> +      {:ok, tweet} = Posts.create_tweet(%{"tweet" => "ddd"}, user.id)
これも`setup`内で作れるのが理想です。`Posts.create_tweet`はテストすべき関数なので、テスト用に`tweet`を作る関数を作る必要がありますが・・・

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello_web/controllers/tweet_controller_test.exs
> +    test "lists all tweets even not logged in", %{conn: conn} do
結果が全く同じでも、文脈を入れないためにeven not logged inじゃなくてif logged inとif not logged inで書いたほうが良いと思います。

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello_web/controllers/tweet_controller_test.exs
> +      conn = get(conn, Routes.tweet_path(conn, :index))
ここ全部パイプでつなぎましょう！`|>`

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello_web/controllers/tweet_controller_test.exs
> +      conn = post(conn, Routes.tweet_path(conn, :create), tweet: %{tweet: nil})
ここもパイプでつなげます！

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello_web/controllers/tweet_controller_test.exs
> +      assert get_flash(conn, :info) == "Tweet deleted successfully."
http statusの確認もしましょう！

2021-02-27 10:50 UTC, poly65536 commented on src/test/hello_web/views/layout_view_test.exs
> +        |> post(Routes.registration_path(conn, :create), %{user: @valid_registration})
view のテストではリクエストを叩かないほうが良いです。viewを直接使ってテストできないか確認お願いします。

2021-03-04 09:49 UTC, MasashiYokota requested changes
コメントしました

2021-03-04 09:49 UTC, MasashiYokota commented on src/lib/hello/posts.ex
> +    |> Repo.preload(:user)
```suggestion
    Tweet
    |> preload(:user)
    |> order_by([t], desc: t.inserted_at)
    |> Repo.all()
```
Ecto.Queryのpreloadを使った方がよいです

2021-03-04 09:49 UTC, MasashiYokota commented on src/lib/hello/posts.ex
> +    |> Repo.preload(:user)
```suggestion
    Tweet
    |> Repo.get(id)
    |> Repo.preload(:user)
```
パイプしましょう

2021-03-04 09:49 UTC, MasashiYokota commented on src/lib/hello/posts/tweet.ex
> +        }
```suggestion
  @type t() :: %__MODULE__{
          __meta__: Ecto.Schema.Metadata.t(),
          tweet: String.t(),
          user: User.t()
        }
```
Userの型も入れましょう。

2021-03-04 09:49 UTC, MasashiYokota commented on src/lib/hello/posts/tweet.ex
> +    |> put_change(:user_id, user_id)
```suggestion
  def changeset(%__MODULE__{} = tweet, params, user_id) do
    tweet
    |> cast(params, [:tweet, :user_id])
    |> validate_required([:tweet, :user_id])
    |> validate_length(:tweet, min: @minimum_tweet_length, max: @maximum_tweet_length)
```
こっちのほうが、バリデーションもできるしシンプルですね。

2021-03-04 09:49 UTC, MasashiYokota commented on src/lib/hello_web/controllers/registration_controller.ex
> +          |> Enum.join("\n")
全部パイプしたほうが良いですね

2021-03-04 09:49 UTC, MasashiYokota commented on src/lib/hello_web/controllers/tweet_controller.ex
> +          |> Enum.join("\n")
ここも全部パイプしたほうが良いですね

2021-03-04 12:08 UTC, MasashiYokota commented on src/test/hello_web/controllers/tweet_controller_test.exs
> +  end
controllerのテストは、シチュエーションごとにdescribeでまとめると良いです。
例えば、
```elixir
describe "login user .." do
  test "GET request..."
  test "POST request..."
end

describe "logout user ..." do
  test "GET request..."
  test "POST request..."
end
```

こうするとsetupがうまい具合に共通化できるので良いです。

2021-03-07 04:44 UTC, konayuki002 commented
自分が見た限りではいいと思います

2021-03-07 04:56 UTC, MasashiYokota commented
LGTM 👍 
マージして次のタスクに取り掛かって下さい

2021-03-07 04:58 UTC, merged